import random
def rand_choice(arr):return arr[random.randint(0,len(arr)-1)]
fnames=['Nicole','Ian','Maria','Mark','Marie','Joseph','Patricia','John','Kate','Kevin','Kim','Jake','Bea','Angelo','Angelica','Anthony','Sarah','Edenjevy','Michelle','Kyle','Ella','Alyssa','Jeff','Joyce','Christopher','Hannah','Felix','Grace','Chrislann','Anne','Jeffrey','Camille','Francis','Anna','Robert','Jane','Karl','Angela','Louis','Joan','Kirk','Isabel','Jan','Thea','Melvin','Danielle','Nathan','Bianca','Mikel','Sophia','Rodrigo','Sam','Carlo','Tricia','Adrian','Mary','Carl','Aya','Jack','Nikki','Nicholas','Jessica','Daniel','Valerie','Clarence','Trisha','Lee','Victoria','Ryan','Mae','Sean','Kathleen','Joshua','Sheila','Chris','Keziah','Lester','Clarissa','Paolo','Marian','Leon','Alexa','Gabriel','Loysa','Justin','Erin','Hans','Emily','Jericho','Cindy','Neil Bryan','Judy','King Arthur','Stephanie','Bryan','Danica','Adriano','Jan','Marco','Christine','Kenneth','Cheskka','Fau','Joramae','Virgilio','Nadine','Julius','Abby','Daryll','Jennly','Ben','Kristine','Moses','Katrina','Henry','Pia','Juhary','Karen','Emman','Anj','Anjo','Lovely','Jonathan','Pauline','Jehrom','Jean','Tyrone','Louise','Jasper','Ruth','Philip Cristian','Maricar','Bejie','Marcia','Jeremy','Mackenzie','Jalvon','Yanna','Gerald','Sabrina','Justine','Ciara','John Vic','Trina','Cally','Nina','Vincent Lynell','Calyx','Rae','Neli','Mica','Vincent','Sandy','Junerich','Coleen','Dale','Franchesca','Geo','Paula','Paul','Kristina','Eras','Kris','Ced','Charisse','Exequiel','Leah','Robin(Seongbin)','Alexis','Ranj','Faye','Jose Arian','Bella','Ramos','Katherine','Seth','Jeanne','Rj','Janice','Ian Benedict','Liezel','Carlos','Rachelle Mae','Jonas','Dominique','Erick','Jenny','Allex Roiman','Mariel','Lindow','Jackie','Macprins','Daniella','Raphael Toledo','Rose','Zoe','Krizhia','Phillip']
lnames=['Abyyappy','Abandarios','Abaygar','Abucay','Abrogar','Abulog','Adona','Agatep','Agbayani','Alimboyugen','Allanic','Alupay','Ahkiong','Amora','Amurao','Baal','Baang','Baldedara','Baltar','Balignasay','Batungbakal','Bello','Biag','Biglang-Awa','Bilatan','Bongalos','Bitao','Bitangcol','Butil','Cabatingan','Cabigas','Cagas','Calapatia','Caldero','Calunod','Camat','Camara','Canumay','Carandang','Casicas','Catacutan','Cawayan','Cayawan','Cayubyub','Cojuangco','Chincuanco','Chuchu','Cuyegkeng','Dacudag','Dacudao','Dagala','Dahil-Dahil','Razon','Daplas','Dimaano','Dimaguiba','Dimaunahan','Dinaluyan','Dinlayan','Dioquino','Divero','Dofitas','Dumaloan','Dumalahay','Dysangco','Gabuat','Galit','Gallano','Gatan','Gosiengfiao','Gubat','Guimatao','Guinto','Dinguinbayan','Dyquiangco','Humilde','Ifugao','Ilaban','Japos','Kalawakan','Kanaway','Kaunlaran','Kulikutan','Kulubot','Kumulitog','Labasan','Labong','Lacro','Lao-lao','Lazaro','Lemoncito','Leones','Limbudan','Limcuando','Linganyan','Luso-Luso','Macawili','Macaraeg','Macaspac','Macalipay','Madlambayan','Madlangbayan','Magan','Magaling','Magbantay','Magbanua','Magday','Magdiwang','Maglikian','Magnaye','Magos','Magpantay','Magpulong','Magsaysay','Mahiya','Makabaligoten','Makadaan','Malit','Mallari','Malubay','Manansala','Manyakes','Marapao','Matapang','Makisig','Malaki','Maputi','Maitim','Maliit','Masipag','Matiyaga','Malagar','Mangayao','Mangsinco','Mangubat','Manigbas','Magsino','Murro','Navea','Labuguen','Lanta=','Limbaco','Limcangco','Limuaco','Loshang','Luansing','Olan','Ongpauco','Ongsioco','Otogan','Pabalan','Paca','Pagsisihan','Paloma','Panonce','Patanindagat','Paragili','Parsaligan','Pecore','Peria','Pilapil','Pildilapil','Pinagbuklod','Pinagdamutan','Pinagpala','Quiambao','Relano','Reotutar','Sariwa','Salem','Salumbidez','Malazarte','Sese','Sinagtala','Sipsip','Siapuatco','Simangan','Simsuangco','Solmoro','Songcuya','Sumague','Supsup','Sydiongco','Syjuco','Sytengco','Subrabas','Tabilla','Tagaan','Talaugon','Tala','Talatala','Talong','Tiaoqui','Tambuatco','Tanhehco','Tanjutco','Tanjuatco','Tansiongco','Tapalla','Tiangco','Tiongson','Tubo','Tubongbanua','Tugonon','Tumulak','Tupas','Quiblat','Quisumbing','Quindipan','Quibin','Quibuyen','Uy']
def get_random_name():
	B=rand_choice(lnames);C=rand_choice(fnames);A=rand_choice(lnames)
	while A==B:A=rand_choice(lnames)
	return B,C,A
if __name__=='__main__':
	for i in range(20):print('%s, %s %s'%get_random_name())